In [1]:
# installations primiarly needed for Mujoco
!apt-get install -y \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    software-properties-common

!apt-get install -y patchelf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
software-properties-common is already the newest version (0.99.22.9).
The following additional packages will be installed:
  libegl-dev libgl-dev libgles-dev libgles1 libglu1-mesa libglu1-mesa-dev libglvnd-core-dev
  libglvnd-dev libglx-dev libopengl-dev libosmesa6
The following NEW packages will be installed:
  libegl-dev libgl-dev libgl1-mesa-dev libgl1-mesa-glx libgles-dev libgles1 libglew-dev
  libglu1-mesa libglu1-mesa-dev libglvnd-core-dev libglvnd-dev libglx-dev libopengl-dev libosmesa6
  libosmesa6-dev
0 upgraded, 15 newly installed, 0 to remove and 38 not upgraded.
Need to get 4,020 kB of archives.
After this operation, 19.4 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglx-dev amd64 1.4.0-1 [14.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgl-dev amd64 1.4.0-1 [101 kB]
Get:3 http://archive.ubuntu.com/ubuntu 

In [16]:
# primarily RL-sepcific requirements
%pip install -f https://download.pytorch.org/whl/torch_stable.html \
                free-mujoco-py \
                einops \
                gym==0.23.1 \
                protobuf==3.20.1 \
                git+https://github.com/rail-berkeley/d4rl.git \
                mediapy \
                Pillow==9.0.0


Looking in links: https://download.pytorch.org/whl/torch_stable.html
  Cloning https://github.com/rail-berkeley/d4rl.git to /tmp/pip-req-build-ls87vwhe
  Running command git clone --filter=blob:none --quiet https://github.com/rail-berkeley/d4rl.git /tmp/pip-req-build-ls87vwhe
  Resolved https://github.com/rail-berkeley/d4rl.git to commit 71a9549f2091accff93eeff68f1f3ab2c0e0a288
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.7/721.7 kB 9.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Cloning https://github.com/aravindr93/mjrl (to revision master) to /tmp/pip-install-y6tgowbp/mjrl_ec86bcc4a66240eea76895d3e65699bc
  Running command git clone --filter=blob:none --quiet https://github.com/aravindr93/mjrl /tmp/pip-install-y6tgowbp/mjrl_ec86bcc4a66240eea76895d3e65699bc
  Resolved https://github.com/aravindr93/mjrl to commit 3871d93763d3b49c47

In [14]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" 535514 Reinforcement Learning, HW1

The sanity check suggested by D4RL official repo
Source: https://github.com/Farama-Foundation/D4RL
"""


import d4rl # Import required to register environments, you may need to also import the submodule
import gym

# Create the environment
env = gym.make('maze2d-umaze-v1')

# d4rl abides by the OpenAI gym interface
env.reset()
env.step(env.action_space.sample())

# Each task is associated with a dataset
# dataset contains observations, actions, rewards, terminals, and infos
dataset = env.get_dataset()
print(dataset['observations']) # An N x dim_observation Numpy array of observations

# Alternatively, use d4rl.qlearning_dataset which
# also adds next_observations.
dataset = d4rl.qlearning_dataset(env)


# export CC="gcc-13

/usr/local/lib/python3.10/dist-packages/gym/utils/seeding.py:38: DeprecationWarning: WARN: Function `rng.randn(*size)` is marked as deprecated and will be removed in the future. Please use `rng.standard_normal(size)` instead.
  deprecation(
load datafile: 100%|██████████| 8/8 [00:00<00:00, 24.20it/s]


[[ 1.0856489   1.9745734   0.00981035  0.02174424]
 [ 1.0843927   1.97413    -0.12562364 -0.04433781]
 [ 1.0807577   1.9752754  -0.3634883   0.11453988]
 ...
 [ 1.1328583   2.8062387  -4.484303    0.09555068]
 [ 1.0883482   2.8068895  -4.4510083   0.06509537]
 [ 1.0463258   2.8074222  -4.202244    0.05324839]]


load datafile: 100%|██████████| 8/8 [00:00<00:00, 22.64it/s]


In [20]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" 535514 Reinforcement Learning, HW1

The sanity check suggested by D4RL official repo
Source: https://github.com/Farama-Foundation/D4RL
"""

import gym
import d4rl # Import required to register environments, you may need to also import the submodule

# Create the environment
# task list: https://github.com/Farama-Foundation/d4rl/wiki/Tasks
env = gym.make('walker2d-expert-v0')

# d4rl abides by the OpenAI gym interface
env.reset()
env.step(env.action_space.sample())

# Each task is associated with a dataset
# dataset contains observations, actions, rewards, terminals, and infos
dataset = env.get_dataset()
print(dataset['observations']) # An N x dim_observation Numpy array of observations

# Alternatively, use d4rl.qlearning_dataset which
# also adds next_observations.
dataset = d4rl.qlearning_dataset(env)

# export CC="gcc-13

/usr/local/lib/python3.10/dist-packages/gym/envs/registration.py:505: UserWarning: WARN: The environment walker2d-expert-v0 is out of date. You should consider upgrading to version `v2` with the environment ID `walker2d-expert-v2`.
  logger.warn(
/usr/local/lib/python3.10/dist-packages/d4rl/gym_mujoco/gym_envs.py:23: UserWarning: This environment is deprecated. Please use the most recent version of this environment.
  offline_env.OfflineEnv.__init__(self, **kwargs)


load datafile: 100%|██████████| 5/5 [00:00<00:00,  7.17it/s]


[[ 1.2510049e+00  1.0074221e-03 -4.5737810e-03 ...  3.0706967e-03
  -1.4775258e-03  2.5933359e-03]
 [ 1.2498622e+00 -1.3810283e-02 -8.7114600e-03 ... -1.2284586e+00
  -6.1169868e+00  1.0000000e+01]
 [ 1.2464757e+00 -5.1110443e-02 -1.0991425e-02 ... -1.0430956e-01
  -1.0000000e+01  1.0000000e+01]
 ...
 [ 1.0103390e+00  3.0215027e-02 -1.0983518e+00 ... -1.0391350e+00
   1.0000000e+01 -3.6839664e+00]
 [ 1.0152587e+00  1.8008804e-02 -1.0791219e+00 ... -9.1392374e-01
   1.0000000e+01 -2.9521749e+00]
 [ 1.0170232e+00  1.4151810e-02 -1.0691322e+00 ... -7.3134965e-01
   1.0000000e+01 -2.2571461e+00]]


load datafile: 100%|██████████| 5/5 [00:00<00:00,  5.60it/s]
